name: churner
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cs_monero:
    git:
      url: https://github.com/cypherstack/cs_monero.git
      ref: 851ab85f003f9026f0f22f6d0684528df91024af
      path: cs_monero

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
