name: churner
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cs_monero:
    git:
      url: https://github.com/cypherstack/cs_monero.git
      ref: c737891f383426f891448c16e5f945575f374237
      path: cs_monero
  monero_rpc: ^1.1.0
  sqlite_async: ^0.11.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
