name: churner
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none
repository: https://github.com/cypherstack/churner

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.2
  ascii_qr: ^1.0.1
  cs_monero:
    git:
      url: https://github.com/cypherstack/cs_monero.git
      ref: 32ac8c2fe0309b01c6d2860ccd34bbc28a9c7ff7 # Includes deserialization changes.
      path: cs_monero
  monero_rpc: ^1.3.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mockito: ^5.3.2
  path: ^1.8.3
